## miscellaneous functions

#' Permute residuals
#'
#' Independently permute the residuals for each subject in the data set.
#'
#' @param data The dataset.
#' @param subject Unquoted name of the variable identifying individual
#'   subjects.
#' @param residuals Unquoted variable name for residuals.
#' @return A table with the \code{residuals} column permuted for each subject.
#' @importFrom magrittr %>%
#' @importFrom rlang !!
#' @importFrom rlang :=
#' @export
permute_resids <- function(data, subject, residuals) {
  subj <- rlang::enquo(subject)
  resid <- rlang::enquo(residuals)
  r2 <- rlang::quo_name(resid)
  data %>%
    dplyr::group_by(!!subj) %>%
    dplyr::mutate(!!r2 := sample(!!resid)) %>%
    dplyr::ungroup()
}

#' Convert residuals to ragged array (list)
#'
#' Convert a column of residuals in a data frame into a list.
#'
#' @param data The dataset.
#' @param subject Unquoted name of the variable identifying individual
#'   subjects.
#' @param residuals Unquoted variable name for residuals.
#' @return A list where each element is the vector of residuals for a subject.
#' @export 
resids_to_rarray <- function(data, subject, residuals) {
  subj <- rlang::enquo(subject)
  resid <- rlang::enquo(residuals)
  data %>%
    dplyr::select(!!subj, !!resid) %>%
    dplyr::group_by(!!subj) %>%
    tidyr::nest(.key = "dat") %>%
    dplyr::pull(dat) %>%
    purrr::map(dplyr::pull)
}

#' Run a permutation test on logit data
#'
#' @param dat Data generated by a call to \code{\link{gen_logit_data}()}.
#' @param nmc Number of Monte Carlo runs.
#' @return p-value.
#' @details This function is only to be used for data generated by \code{gen_logit_data()}.
#' @export
permutation_test <- function(dat, nmc = 1000L) {
  
}
