#' Run a permutation test
#'
#' Run a permutation on logistic regression datasets.
#'
#' @param dat Data frame generated by the function \code{\link{gen_logit_data}()}.
#' @param nmc Number of Monte Carlo runs.
#' @return p value.
#' @export
permutation_test <- function(dat, nmc = 1000L) {
  test_stat <- function(mydata) {
    dmeans <- dplyr::summarize(dplyr::group_by(mydata, Ad), m = mean(Y))
    dmeans[["m"]][2] - dmeans[["m"]][1]
  }
  orig <- test_stat(dat)
  res <- purrr::map_dbl(1:nmc, function(x) {
    dat_nest <- tidyr::nest(dplyr::group_by(dat, subj_id, A, Ad))
    dat_subj <- dplyr::distinct(dat_nest, subj_id)
    dat_subj[["multiplier"]] <- sample(c(-1L, 1L), nrow(dat_subj), TRUE)
    dat_join <- dplyr::inner_join(dat_subj, dat_nest, "subj_id")
    dat_join[["Ad"]] <- dat_join[["Ad"]] * dat_join[["multiplier"]]
    dat_perm <- tidyr::unnest(dat_join)
    test_stat(dat_perm)
  })
  nge <- sum(abs(c(orig, res)) >= abs(orig))
  nge / (nmc + 1)
}

#' Fit GLMM to logit with empirical logit as DV
#'
#' @param dat Data frame generated by the function \code{\link{gen_logit_data}()}.
#' @return p value.
#' @export
elogit_test <- function(dat) {
  dlog <- dplyr::ungroup(
                   dplyr::summarize(
                            dplyr::group_by(dat, subj_id, item_id, Ad),
                            elog = log((sum(Y) + .5) /
                                       (length(Y) - sum(Y) + .5))))
  tryCatch({
    mod <- lme4::lmer(elog ~ Ad + (Ad | subj_id), dlog)
    tval <- lme4::fixef(mod) / sqrt(Matrix::diag(vcov(mod)))
    res <- 2 * (1 - pnorm(abs(tval)))
    res[[2]]
  },
  error = function(e) NA_real_,
  warning = function(w) NA_real_)
}
