#' Run a permutation test
#'
#' Run a permutation on logistic regression datasets.
#'
#' @param dat Data frame generated by the function \code{\link{gen_logit_data}()}.
#' @param nmc Number of Monte Carlo runs.
#' @return p value.
permutation_test <- function(dat, nmc = 1000L) {
  test_stat <- function(mydata) {
    mod <- glm(Y ~ Ad, binomial, mydata)
    coef(mod)[[2]]
  }
  orig <- test_stat(dat)
  res <- purrr::map_dbl(1:nmc, function(x) {
    dat_nest <- tidyr::nest(dplyr::group_by(dat, subj_id, A, Ad))
    dat_subj <- dplyr::distinct(dat_nest, subj_id)
    dat_subj[["multiplier"]] <- sample(c(-1L, 1L), nrow(dat_subj), TRUE)
    dat_join <- dplyr::inner_join(dat_subj, dat_nest, "subj_id")
    dat_join[["Ad"]] <- dat_join[["Ad"]] * dat_join[["multiplier"]]
    dat_perm <- tidyr::unnest(dat_join)
    test_stat(dat_perm)
  })
  nge <- sum(abs(c(orig, res)) >= abs(orig))
  nge / (nmc + 1)
}

